# Pandas Filtering Data

In real jobs, datasets can contain:

10,000 rows \
100,000 rows \
1,000,000+ rows

We don't want all data.

We want only:

Students with marks above 80 \
Employees with salary above 50,000 \
Customers from London \
Products costing less than £100

This process is called **Filtering**

Think: Filtering = Keeping only the rows you want

### Create Dataset

In [1]:
import pandas as pd

students = {
    "Name": ["Ali", "Sara", "John", "David", "Emma"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 90, 78, 65, 95]
}

df = pd.DataFrame(students)

print(df)

    Name  Age  Marks
0    Ali   20     85
1   Sara   21     90
2   John   19     78
3  David   22     65
4   Emma   20     95

## Greater Than (>)

Find students with marks above 80.

In [2]:
print(df["Marks"] > 80)

0     True
1     True
2    False
3    False
4     True
Name: Marks, dtype: bool

### What Does True Mean?

True  = Keep this row

False = Ignore this row

### Actual Filtering

In [3]:
print(df[df["Marks"] > 80])

   Name  Age  Marks
0   Ali   20     85
1  Sara   21     90
4  Emma   20     95

### Memory Trick

df[condition]

Think: DataFrame[Rule]

Example:

In [5]:
df[df["Marks"] > 80]

   Name  Age  Marks
0   Ali   20     85
1  Sara   21     90
4  Emma   20     95

means: Show only rows where Marks > 80

## Less Than (<)

Students with marks below 80.

In [6]:
print(df[df["Marks"] < 80])

    Name  Age  Marks
2   John   19     78
3  David   22     65

## Equal To (==)

Students aged 20.

In [7]:
print(df[df["Age"] == 20])

   Name  Age  Marks
0   Ali   20     85
4  Emma   20     95

## Not Equal (!=)

Students not aged 20.

In [9]:
print(df[df["Age"] != 20])

    Name  Age  Marks
1   Sara   21     90
2   John   19     78
3  David   22     65

## Greater Than or Equal (>=)

In [10]:
print(df[df["Marks"] >= 90])

   Name  Age  Marks
1  Sara   21     90
4  Emma   20     95

## Less Than or Equal (<=)

In [11]:
print(df[df["Marks"] <= 70])

    Name  Age  Marks
3  David   22     65

## Multiple Conditions

Sometimes one condition isn't enough.

Example:

Marks > 80

AND

Age = 20

### AND Operator (&)

In [13]:
print(df[(df["Marks"] > 80) & (df["Age"] == 20)])

   Name  Age  Marks
0   Ali   20     85
4  Emma   20     95

**&** means **AND** \
Both conditions must be true.

### OR Operator (|)

Example: \
Age = 19

OR

Marks > 90

In [14]:
print(df[(df["Age"] == 19) | (df["Marks"] > 90)])

   Name  Age  Marks
2  John   19     78
4  Emma   20     95

**|** means **OR** \
At least one condition must be true.

## Filter Specific Columns After Filtering

Students scoring above 80.

Show only Names.

In [16]:
print(df[df["Marks"] > 80]["Name"])

0     Ali
1    Sara
4    Emma
Name: Name, dtype: object

### Using loc with Filtering

Professional approach:

In [17]:
print(df.loc[df["Marks"] > 80, ["Name", "Marks"]])

   Name  Marks
0   Ali     85
1  Sara     90
4  Emma     95

### Find Top Students

In [19]:
top_students = df[df["Marks"] >= 90]

print(top_students)

   Name  Age  Marks
1  Sara   21     90
4  Emma   20     95

### Real Company Example

Employee Dataset:

In [21]:
employees = {
    "Name": ["A", "B", "C", "D"],
    "Salary": [30000, 50000, 70000, 45000],
    "Department": ["IT", "HR", "IT", "Finance"]
}

df = pd.DataFrame(employees)

Employees earning above 50,000:

In [22]:
print(df[df["Salary"] > 50000])

  Name  Salary Department
2    C   70000         IT

### Find Maximum Marks Student

In [25]:
import pandas as pd

students = {
    "Name": ["Ali", "Sara", "John", "David", "Emma"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 90, 78, 65, 95]
}

df = pd.DataFrame(students)

highest = df["Marks"].max()

print(highest)

95

Get row:

In [26]:
print(df[df["Marks"] == highest])

   Name  Age  Marks
4  Emma   20     95

## Practice

In [28]:
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D"],
    "Marks": [50, 70, 90, 80]
}

df = pd.DataFrame(data)

df[df["Marks"] > 70]

  Name  Marks
2    C     90
3    D     80

In [29]:
df[df["Marks"] == 90]

  Name  Marks
2    C     90

In [30]:
df[df["Marks"] < 80]

  Name  Marks
0    A     50
1    B     70

In [32]:
df["Age"] = [20,21,20,22]
df[df["Age"] == 20]

  Name  Marks  Age
0    A     50   20
2    C     90   20

In [33]:
df[(df["Marks"] > 70) & (df["Age"] == 20)]

  Name  Marks  Age
2    C     90   20

## Mini Project Student Performance Analyzer

In [35]:
import pandas as pd

students = {
    "Name": ["Ali", "Sara", "John", "David", "Emma"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 90, 78, 65, 95]
}

df = pd.DataFrame(students)

print("Full Dataset")
print(df)

print("\nStudents Above 80")
print(df[df["Marks"] > 80])

print("\nStudents Age 20")
print(df[df["Age"] == 20])

print("\nTop Students")
print(df[df["Marks"] >= 90])

print("\nAge 20 and Marks > 80")
print(df[(df["Age"] == 20) & (df["Marks"] > 80)])

Full Dataset
    Name  Age  Marks
0    Ali   20     85
1   Sara   21     90
2   John   19     78
3  David   22     65
4   Emma   20     95

Students Above 80
   Name  Age  Marks
0   Ali   20     85
1  Sara   21     90
4  Emma   20     95

Students Age 20
   Name  Age  Marks
0   Ali   20     85
4  Emma   20     95

Top Students
   Name  Age  Marks
1  Sara   21     90
4  Emma   20     95

Age 20 and Marks > 80
   Name  Age  Marks
0   Ali   20     85
4  Emma   20     95

### Memory Tricks 🧠

**>** Greater Than

<   Less Than

==  Equal To

!=  Not Equal

& = AND \
Both conditions true.

| = OR \
At least one condition true.

df[df["Marks"] > 80]

Read as:

Give me rows where Marks are above 80