# Missing Values (NaN) in Pandas

Imagine a college database:

Name   |  Age |     Marks
-------|------|---------
Ali    |   20 |     85
Sara   |   ?  |     90
John   |   19 |     ?
Mary   |   21 |     78

Some information is missing.

Pandas represents missing data as: **NaN** \
Meaning: Not a Number

Think of NaN as: "I don't know the value."

## Step 1: Create Dataset with Missing Values

In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ali", "Sara", "John", "Mary"],
    "Age": [20, np.nan, 19, 21],
    "Marks": [85, 90, np.nan, 78]
}

df = pd.DataFrame(data)

print(df)

   Name   Age  Marks
0   Ali  20.0   85.0
1  Sara   NaN   90.0
2  John  19.0    NaN
3  Mary  21.0   78.0

What is np.nan? \
np means NumPy.

**import numpy as np**

NaN is a special value used to indicate missing data.

**np.nan**

## Step 2: Detect Missing Values

Use: **df.isnull()** \
Example:

In [2]:
print(df.isnull())

    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

Meaning: \
True  = Missing value found \
False = Value exists

**isnull()** asks: "Is something missing?"

### Count Missing Values

Instead of seeing every row:

In [3]:
df.isnull().sum()

Name     0
Age      1
Marks    1
dtype: int64

Meaning: \
Age column → 1 missing value \
Marks column → 1 missing value

**Most Common Interview Question**

How many missing values are in the dataset? \
Answer: df.isnull().sum()

## Step 3: Remove Rows with Missing Values

Suppose we only want complete rows. \
Use: **df.dropna()**

In [4]:
print(df.dropna())

   Name   Age  Marks
0   Ali  20.0   85.0
3  Mary  21.0   78.0

Rows containing NaN are removed.

**Understanding**

Before: 

|     |      |       |
|-----|------|-------|
|Ali  |   20 |    85 | 
|Sara |   NaN|    90 |
|John |   19 |    NaN| 
|Mary |   21 |    78 |

After: 

|     |       |      |
|-----|-------|------|
|Ali  |   20  |   85 |
|Mary |   21  |   78 |

## Step 4: Remove Columns with Missing Values

Use:

In [5]:
df.dropna(axis=1)

   Name
0   Ali
1  Sara
2  John
3  Mary

Because:\
Age has NaN \
Marks has NaN \
Both columns are removed.
    
Remember Axis \
axis=0 → Rows \
axis=1 → Columns

## Step 5: Fill Missing Values
Most Data Scientists don't delete data. \
They fill missing values.

### Fill with Zero

In [6]:
df.fillna(0)

   Name   Age  Marks
0   Ali  20.0   85.0
1  Sara   0.0   90.0
2  John  19.0    0.0
3  Mary  21.0   78.0

### Fill Age with 18

In [8]:
df["Age"] = df["Age"].fillna(18)

print(df)

   Name   Age  Marks
0   Ali  20.0   85.0
1  Sara  18.0   90.0
2  John  19.0    NaN
3  Mary  21.0   78.0

**Example**

Suppose: Age missing \
Instead of deleting the student: Use average age

## Step 6: Fill with Mean

Dataset: \
20 \
NaN \
19 \
21 

Average: (20 + 19 + 21)/3 = 20

Fill missing value with 20.

Code:

In [10]:
df["Age"] = df["Age"].fillna(
    df["Age"].mean()
)

print(df["Age"])

0    20.0
1    18.0
2    19.0
3    21.0
Name: Age, dtype: float64

**Why Mean?**

Because it keeps data realistic. \
Better than 0 for age.

Nobody is 0 years old in a university dataset.

### Other Useful Statistics

Mean: **df["Age"].mean()**

Median: **df["Age"].median()**

Mode: **df["Age"].mode()[0]**

## Step 7: Check Again

After filling:

In [11]:
df.isnull().sum()

Name     0
Age      0
Marks    1
dtype: int64

In [12]:
#Fix Marks Too

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

In [13]:
df.isnull().sum()

Name     0
Age      0
Marks    0
dtype: int64

No missing values.

**Workflow**

Whenever you get a CSV:\
1> df.head() 

Look at data. \
2> df.info()

Understand columns. \
3> df.isnull().sum()

Check missing values.\
4> fillna() or dropna()

Fix missing values.

### Practice

In [14]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Marks": [80, np.nan, 70, 90]
})

print(df)

#Find missing values:

df.isnull().sum()

   Marks
0   80.0
1    NaN
2   70.0
3   90.0

Marks    1
dtype: int64

In [17]:
#Fill missing values with: 0
#using: fillna()

df.fillna(0)

   Marks
0   80.0
1    0.0
2   70.0
3   90.0

In [19]:
#Fill missing values using: mean()

df["Marks"].mean()

80.0

In [20]:
df["Marks"] = df["Marks"].fillna(
    df["Marks"].mean()
)

print(df["Marks"])

0    80.0
1    80.0
2    70.0
3    90.0
Name: Marks, dtype: float64

In [21]:
#Remove rows containing NaN:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Marks": [80, np.nan, 70, 90]
})

df.dropna()

   Marks
0   80.0
2   70.0
3   90.0

In [22]:
data = {
    "Age":[20,np.nan,19],
    "Marks":[90,85,np.nan]
}

#Find:

df.isnull().sum()

Marks    1
dtype: int64

## Mini Project: Student Database Cleaner

In [23]:
import pandas as pd
import numpy as np

students = {
    "Name": ["Ali", "Sara", "John", "Mary"],
    "Age": [20, np.nan, 19, 21],
    "Marks": [85, 90, np.nan, 78]
}

df = pd.DataFrame(students)

print("Original Data")
print(df)

print("\nMissing Values")
print(df.isnull().sum())

df["Age"] = df["Age"].fillna(
    df["Age"].mean()
)

df["Marks"] = df["Marks"].fillna(
    df["Marks"].mean()
)

print("\nCleaned Data")
print(df)

print("\nMissing Values After Cleaning")
print(df.isnull().sum())

Original Data
   Name   Age  Marks
0   Ali  20.0   85.0
1  Sara   NaN   90.0
2  John  19.0    NaN
3  Mary  21.0   78.0

Missing Values
Name     0
Age      1
Marks    1
dtype: int64

Cleaned Data
   Name   Age      Marks
0   Ali  20.0  85.000000
1  Sara  20.0  90.000000
2  John  19.0  84.333333
3  Mary  21.0  78.000000

Missing Values After Cleaning
Name     0
Age      0
Marks    0
dtype: int64

### Memory Tricks 🧠

Find Missing Values **df.isnull()** \
Think:Is anything missing?

Count Missing Values **df.isnull().sum()** \
Think: How many are missing?

Remove Missing Rows **df.dropna()** \
Think: Drop rows with missing data

Fill Missing Values **df.fillna(value)**\
Think: Replace missing data

Fill with Average \
**df["col"].fillna( \
    df["col"].mean() \
)**