# Pandas Adding & Removing Columns

Imagine This Table

| Name| Age  |  Marks|
|-----|------|-------|
|Ali  |  20  |    85 |
|Sara |  21  |    90 |
|John |  19  |    78 |

Teacher now wants: Pass / Fail column

New table:
    
|Name  |  Age | Marks | Status
|------|------|-------|--------
|Ali   |   20 |   85  |    Pass
|Sara  |   21 |   90  |    Pass
|John  |   19 |   78  |    Pass

We must add a new column.

### Create Dataset

In [2]:
import pandas as pd

students = {
    "Name": ["Ali", "Sara", "John"],
    "Age": [20, 21, 19],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(students)

print(df)

   Name  Age  Marks
0   Ali   20     85
1  Sara   21     90
2  John   19     78

## Adding a New Column

Syntax:
df["NewColumn"] = values

In [3]:
df["City"] = ["London", "Manchester", "Birmingham"]

print(df)

   Name  Age  Marks        City
0   Ali   20     85      London
1  Sara   21     90  Manchester
2  John   19     78  Birmingham

**Memory Trick**

New Column

↓

df["ColumnName"] = data

### Create Column from Existing Columns

Very common in Data Science.

Example:

Teacher gives bonus marks.

In [4]:
df["Final_Marks"] = df["Marks"] + 5

print(df)

   Name  Age  Marks        City  Final_Marks
0   Ali   20     85      London           90
1  Sara   21     90  Manchester           95
2  John   19     78  Birmingham           83

Why Is This Useful?

Real companies create: Profit = Revenue - Cost

BMI = Weight / Height²

Final Marks = Marks + Bonus

### Create Pass/Fail Column

Suppose:

Pass if Marks >= 80

In [5]:
df["Status"] = df["Marks"] >= 80

print(df)

   Name  Age  Marks        City  Final_Marks  Status
0   Ali   20     85      London           90    True
1  Sara   21     90  Manchester           95    True
2  John   19     78  Birmingham           83   False

In [6]:
df["Status"] = ["Pass", "Pass", "Fail"]

print(df)

   Name  Age  Marks        City  Final_Marks Status
0   Ali   20     85      London           90   Pass
1  Sara   21     90  Manchester           95   Pass
2  John   19     78  Birmingham           83   Fail

### Updating Existing Values

Suppose Ali's marks become 95.

In [12]:
#Using loc:

df.loc[0, "Marks"] = 95

print(df["Marks"])

0    95
1    90
2    78
Name: Marks, dtype: int64

### Update Multiple Values

In [19]:
df = pd.DataFrame({
    "Name": ["Ali", "Sara", "John"],
    "Marks": [85, 90, 78]
})

df["Marks"] = df["Marks"] + 10

print(df)

   Name  Marks
0   Ali     95
1  Sara    100
2  John     88

### Rename Columns

Suppose: Marks -> Exam_Marks

In [20]:
df.rename(columns={"Marks": "Exam_Marks"})

   Name  Exam_Marks
0   Ali          95
1  Sara         100
2  John          88

### Permanent Rename

In [21]:
df = df.rename(columns={"Marks": "Exam_Marks"})

print(df)

   Name  Exam_Marks
0   Ali          95
1  Sara         100
2  John          88

rename(): Changes column names
    
## Remove a Column

Suppose: Age column not needed

In [23]:
import pandas as pd

students = {
    "Name": ["Ali", "Sara", "John"],
    "Age": [20, 21, 19],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(students)

df = df.drop("Age", axis=1)

print(df)

   Name  Marks
0   Ali     85
1  Sara     90
2  John     78

Why axis=1?

Remember: \
axis=0 → Rows \
axis=1 → Columns

We are deleting a column.

Therefore: axis=1
    
### Remove Multiple Columns

In [27]:
students = {
    "Name": ["Ali", "Sara", "John"],
    "Age": [20, 21, 19],
    "Marks": [85, 90, 78]
}
df = pd.DataFrame(students)
df = df.drop(["Age", "Marks"], axis=1)
print(df)

   Name
0   Ali
1  Sara
2  John

## Add Index Column

Sometimes useful.

In [33]:
df["Student_ID"] = [101, 102, 103]
df["Marks"] = [90, 85, 78]
print(df)

   Name  Student_ID  Marks
0   Ali         101     90
1  Sara         102     85
2  John         103     78

Rearranging Columns

Suppose we want: \
Student_ID \
Name \
Marks

In [35]:
df = df[
    ["Student_ID", "Name", "Marks"]
]

print(df)

   Student_ID  Name  Marks
0         101   Ali     90
1         102  Sara     85
2         103  John     78

Employee Dataset:

In [36]:
employees = {
    "Name": ["A", "B", "C"],
    "Salary": [30000, 50000, 70000]
}

df = pd.DataFrame(employees)

Create Bonus:

In [38]:
df["Bonus"] = df["Salary"] * 0.10
print(df)

  Name  Salary   Bonus
0    A   30000  3000.0
1    B   50000  5000.0
2    C   70000  7000.0

Create Total Salary:

In [42]:
df["Total"] = df["Salary"] + df["Bonus"]
print(df["Total"])

0    33000.0
1    55000.0
2    77000.0
Name: Total, dtype: float64

## Practice

In [44]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Marks": [50, 60, 70]
})

#add

df["Bonus"] = 5
print(df["Bonus"])

0    5
1    5
2    5
Name: Bonus, dtype: int64

In [45]:
df["Final"] = df["Marks"] + 5
print(df)

  Name  Marks  Bonus  Final
0    A     50      5     55
1    B     60      5     65
2    C     70      5     75

In [46]:
df.rename(columns={"Marks": "Exam_Marks"})

  Name  Exam_Marks  Bonus  Final
0    A          50      5     55
1    B          60      5     65
2    C          70      5     75

In [47]:
df = df.drop(["Bonus"], axis=1)

In [48]:
print(df)

  Name  Marks  Final
0    A     50     55
1    B     60     65
2    C     70     75

In [51]:
df.loc[0, "Marks"] = 100

In [53]:
print(df)

  Name  Marks  Final  Exam_Marks
0    A    100     55       100.0
1    B     60     65         NaN
2    C     70     75         NaN

## Mini Project — Student Result System

In [54]:
import pandas as pd

students = {
    "Name": ["Ali", "Sara", "John"],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(students)

print("Original Dataset")
print(df)

df["Bonus"] = 5

df["Final_Marks"] = df["Marks"] + df["Bonus"]

df["Status"] = ["Pass", "Pass", "Fail"]

print("\nUpdated Dataset")
print(df)

df = df.rename(
    columns={"Marks": "Exam_Marks"}
)

print("\nRenamed Column")
print(df)

df = df.drop("Bonus", axis=1)

print("\nFinal Dataset")
print(df)

Original Dataset
   Name  Marks
0   Ali     85
1  Sara     90
2  John     78

Updated Dataset
   Name  Marks  Bonus  Final_Marks Status
0   Ali     85      5           90   Pass
1  Sara     90      5           95   Pass
2  John     78      5           83   Fail

Renamed Column
   Name  Exam_Marks  Bonus  Final_Marks Status
0   Ali          85      5           90   Pass
1  Sara          90      5           95   Pass
2  John          78      5           83   Fail

Final Dataset
   Name  Exam_Marks  Final_Marks Status
0   Ali          85           90   Pass
1  Sara          90           95   Pass
2  John          78           83   Fail

## Memory Tricks 🧠

**Add Column** \
df["New"] = values

**Update Value** \
df.loc[row, column] = value

**Rename Column** \
df.rename(columns={ \
    "Old":"New" \
})

**Delete Column** \
df.drop("Column", axis=1) \
Axis Rule \
axis=0

Rows \
⬇ \
axis=1

Columns \
➡